### ISSUE TITLE
obsolete documentation

### ISSUE THREAD

**Issue by inferense** [comtravo/ctparse#106]
thanks for the helpful documentation, however as I was playing around and implementing custom changes there are few inaccuracies in the [Contributing](https://ctparse.readthedocs.io/en/latest/contributing.html#add-rules-increase-coverage) section.

`py.test tests/test_run_corpus.py` should be changed to `py.test tests/test_corpus.py` I presume as the `test_run_corpus.py `doesn't exist anymore.

the `make train` command is giving me trouble as well when running it from the root directory.

**Comment by gabrielelanaro** [comment]
thanks for the report! I updated the docs.

can you provide more details regarding the `make train` troubles you are getting?

**Comment by inferense** [comment]
sorry `make train` is an error on my side
